### ISSUE TITLE
The output is not correct 

### ISSUE THREAD

**Issue by ma-siddiqui** [chaits98/ocr-android#3]
I run this on Android mobile but the output is absolutely wrong.
![IMG-20210213-WA0015](https://user-images.githubusercontent.com/42836589/107869559-ee822600-6ea8-11eb-915c-9a02d9c5ae5c.jpeg)
![IMG-20210213-WA0013](https://user-images.githubusercontent.com/42836589/107869566-ff329c00-6ea8-11eb-9f60-47d20df831d8.jpeg)

**Comment by chaits98** [comment]
@ma-siddiqui I'm sorry, I should add in limitations the fact that this works only on plain paper and not ruled sheet of paper.

You are welcome to tweak with the clearing of noise that takes place before the segmentation of individual characters, as I am currently not working on this project.

**Comment by ma-siddiqui** [comment]
@chaits98 thank you for the reply. I tried with the text on plain paper but it still does not and app is crashing.

**Comment by ma-siddiqui** [comment]
Here is the plain paper text.
![Uploading 16132840100007459471005962521858.jpg…]()

**Comment by chaits98** [comment]
@ma-siddiqui I'm sorry,I cannot see the image you uploaded, please share it again

Also please share the crash that occurred.

**Comment by baskarankannan** [comment]
Hi, I am also getting same issue even i tried plain paper also,  please advice me if anything i am wrong

**Comment by chaits98** [comment]
@baskarankannan I haven't worked on this for a while now 

You can explore noise reduction in the converted image. It will help you get better results.

Also I'm closing this thread since it was inactive for so long.
Please open a new one in case further assistance is required
